/* eslint-disable */

/**
 * @namespace Mocha
 * @see https://mochajs.org/api
*/

if (typeof Mocha !== "undefined") {

  /** @memberof Mocha */
  var Suite = Mocha.Suite;

  /**
	 * Return the title path generated by recursively concatenating the parent's
	 * title path.
	 *
	 * @memberof Mocha.Suite
	 * @public
	 * @return {string}
	 */
  Suite.prototype.titlePath = function () {
    var result = [];
    if (this.parent) {
      result = result.concat(this.parent.titlePath());
    }
    if (!this.root) {
      result.push(this.title);
    }
    return result;
  };

  /** @memberof Mocha */
  var Runnable = Mocha.Runnable;

	/**
	 * Return the title path generated by concatenating the parent's title path with the title.
	 *
	 * @memberof Mocha.Runnable
	 * @public
	 * @return {string}
	 */
  Runnable.prototype.titlePath = function () {
    return this.parent.titlePath().concat([this.title]);
  };
}
